---
# tasks file for nginx
- block:
  - name: install EPEL repository gpg key
    rpm_key:
      key: https://getfedora.org/static/352C64E5.txt
      state: present
    register: key_result

  - name: install epel-release package
    package:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
    register: epel_result
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: install nginx package
  package:
    name: nginx
    state: latest
  register: nginx_install

- name: start nginx service
  service:
    name: nginx
    state: started
  when: nginx_install.changed

- name: install nginx configuration file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0640
    owner: root
    group: root
    setype: httpd_config_t
  notify: restart nginx

- name: install firewalld package
  package:
    name: firewalld
    state: latest

- name: start firewalld service
  service:
    name: firewalld
    state: started

- name: open http firewall service
  firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true
  notify: restart firewalld

