---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  name: angry-canary-server-docker
spec:
  dockerImageRepository: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/angry-canary-server-docker
  tags:
  - from:
      kind: DockerImage
      name: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/angry-canary-server-docker:latest
    importPolicy:
      scheduled: true
      insecure: true
    referencePolicy:
      type: Local
    name: latest


