---
apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:                       
    git:
      uri: https://github.com/dollarbhillz/custom-jenkins-build
    type: Git
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-slave-base-rhel7:latest
        namespace: openshift
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest


