apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2017-07-25T17:46:57Z
  generation: 6
  labels:
    app: angry-canary-docker
  name: angry-canary-docker
  namespace: angry-canary
  resourceVersion: "10845778"
  selfLink: /oapi/v1/namespaces/angry-canary/deploymentconfigs/angry-canary-docker
  uid: 412394c3-7161-11e7-9514-009b1a10019c
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
    - type: "Container"
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
      maxLimitRequestRatio:
        cpu: "10"
  replicas: 1
  selector:
    app: angry-canary-docker
    deploymentconfig: angry-canary-docker
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 60
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: angry-canary-docker
        deploymentconfig: angry-canary-docker
    spec:
      containers:
      - image: 172.18.179.6:5000/angry-canary/angry-canary-docker@sha256:5b3f1c097b8e9b74004999713ce2ecc0cc00a71877a07a314f7d01438e784008
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /cpu
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: angry-canary-docker
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - angry-canary-docker
      from:
        kind: ImageStreamTag
        name: angry-canary-docker:latest
        namespace: angry-canary
      lastTriggeredImage: 172.18.179.6:5000/angry-canary/angry-canary-docker@sha256:5b3f1c097b8e9b74004999713ce2ecc0cc00a71877a07a314f7d01438e784008
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-07-25T17:52:21Z
    lastUpdateTime: 2017-07-25T17:52:23Z
    message: replication controller "angry-canary-docker-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2017-07-25T17:55:09Z
    lastUpdateTime: 2017-07-25T17:55:09Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
