apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "0.1" 
        memory: "8Gi" 
      min:
        cpu: "0.1m" 
        memory: "6Mi" 
    - type: "Container"
      max:
        cpu: "1" 
        memory: "8Gi" 
      min:
        cpu: "0.1m" 
        memory: "4Mi" 
      default:
        cpu: "0.11m" 
        memory: "8Gi" 
      defaultRequest:
        cpu: "0.1m" 
        memory: "100Mi" 
      maxLimitRequestRatio:
              cpu: "10"
