---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  name: rh-postgresql95-docker
spec:
  dockerImageRepository: registry.access.redhat.com/rhscl/postgresql-95-rhel7
  tags:
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/postgresql-95-rhel7:latest
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Local
    name: latest


